storage:
  root: '.' # 表示插件的存储根目录
channel:
  size: 20
database:
  engine: 'sqlite' # 存储引擎
  local_file: 'binary' # 插件二进制文件存储路径
  host: 'test.db' # 数据库地址，如果是 SQLite 则是文件路径
  port: 3306 # 数据库端口，如果是 SQLite 请忽略本项
  username: 'root' # 数据库用户名，如果是 SQLite 请忽略本项
  password: 'root' # 数据库密码，如果是 SQLite 请忽略本项
  database: 'test' # 数据库名称，如果是 SQLite 请忽略本项
  version: '3' # 数据库版本
chat:
  global_prefix: '#' # 全局前缀
  host: "localhost" # Wrapper 运行的 gRpc 地址
  port: 8080 # Wrapper 运行的 gRpc 端口
  token: "xxx" # Wrapper 鉴权 Token
provider:
  - type: "QQ" # 平台特定类型
    name: "阿木" # 机器人名称
    account: "854015635" # 机器人账号
    host: "localhost:8081" # 机器人 Provider 地址
    token: "xxx" # 鉴权参数，默认为空，空表示不鉴权，如果需要鉴权请填写本字段并且保证与 Provider 配置一致
open_telemetry:
  enable: true # 是否启用 OpenTelemetry
  host: "localhost" # OTEL 地址
  port: 16686 # OpenAPI 端口